BanterForums/Models/Forum/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace BanterForums.Models.Forum
{   
    
    //represents an index of topics with a main topic (i.e. topics within a programming language category)
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ForumList { get; set; }
    }
}

BanterForums/Models/Forum/ForumListingModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace BanterForums.Models.Forum
{ //Each Forum listed within a Forum Index is display using this class ("Sub-forum")
    public class ForumListingModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

BanterForums/Models/Forum/ForumTopicModel.cs
using BanterForums.Models.Post;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BanterForums.Models.Forum
{
    //Model of a forum topic (i.e. python, c#, etc.)
    public class ForumTopicModel
    {
        public ForumListingModel Forum { get; set; }
        public IEnumerable<PostListingModel> Posts { get; set; }
    }
}

BanterForums/Controllers/ForumController.cs
using Microsoft.AspNetCore.Mvc;
using BanterForums.Data;
using System.Collections.Generic;
using BanterForums.Data.Models;
using System.Linq;
using BanterForums.Models.Forum;
using BanterForums.Models.Post;
using System;

namespace BanterForums.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService)
        {
            _forumService = forumService;
        }

        public IActionResult Index()
        {
            /*var type is IEnumerable<ForumListingModel>*/
            var forums = _forumService.GetAll()
                    .Select(forum => new ForumListingModel {
                        Id = forum.Id,
                        Name = forum.Title,
                        Description = forum.Description
                    }); //Mapping each forum from database to a ForumListingModel Object

            var model = new ForumIndexModel
            {
                ForumList = forums
            }; //assigning the collection of the ForumListingModels to the ForumList member of the ForumIndexModel object


            return View(model); 
        }

        public IActionResult Topic(int id)
        {
            var forum = _forumService.GetById(id);
            var posts = forum.Posts;

            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorRating = post.User.Rating,
                AuthorName = post.User.UserName,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return
                new ForumListingModel
                {
                    Id = forum.Id,
                    Name = forum.Title,
                    Description = forum.Description,
                    ImageUrl = forum.ImageUrl
                };
        }
    }
}

BanterForums/Views/Forum/Index.cshtml
@model BanterForums.Models.Forum.ForumIndexModel

<h1>Forums</h1>

<table class ="table table-hover" id ="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@forum.Id"> <!--Use the forum controller & topic method to return view-->
                        @forum.Name
                    </a>
                </td>
                <td>
                    @forum.Description
                </td>
            </tr>
        }
    </tbody>
</table>

BanterForums/Views/Forum/Topic.cshtml
@model BanterForums.Models.Forum.ForumTopicModel

<h1>Welcome to the @Model.Forum.Name Forum!</h1>
<span>
    <a asp-controller="Post" 
       asp-action="Create" 
       asp-route-id=@Model.Forum.Id class="btn btn-newPost">
       Create Post
    </a>
</span>

@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id ="@post.Id">
                        @post.Title
                        </a>
                    </td>
                    <td>
                        @post.AuthorName
                    </td>
                    <td>
                        @post.DatePosted
                    </td>
                    <td>
                        @post.RepliesCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

else

{
    <div class="noPosts">
         <h3>
             It looks like there are no @Model.Forum.Name posts yet. <br/>
             Why not
             <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">
             <span>Create</span>
             </a>
             One?
         </h3>
    </div>
}